version: "3.8"

services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgre
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgresdb_data:/data/db

volumes:
  postgresdb_data:
